apiVersion: v1
kind: Plugin
metadata:
  author: xiaoxin
  name: WeChatReply
  repository: 'https://github.com/styy88/WeChatReply'
  version: 3.1.0
  description:
    en_US: "Automatic keyword reply plugin"
    zh_Hans: "微信关键词自动回复插件"
  label:
    en_US: "WeChatReply"
    zh_Hans: "微信回复"
spec:
  config:
    - name: enable
      type: boolean
      default: true
    - name: response_delay
      type: integer
      default: 3
execution:
  python:
    path: main.py
    attr: WeChatReplyPlugin
